### ISSUE TITLE
Brew cask should not ask for password

### ISSUE THREAD

**Issue by nunofgs** [uphold/strap#5]
<img width="659" alt="screenshot 2018-11-13 at 21 51 18" src="https://user-images.githubusercontent.com/92085/49521738-01971580-f89e-11e8-91df-3c449c9d58c5.png">

**Comment by ricardobcl** [comment]
This seems to only happen if the `sudo_init()` is not called before timing-out (which by default is 5min).
Although this mechanism was only introduced in [this commit](https://github.com/uphold/strap/commit/549bb890f6bd283d294d71ca7926c39c3d4578ce), maybe that was the problem (5 min passed since the beginning of the script).

I don't think there is anything to do, even on [travis](https://travis-ci.org/uphold/strap/builds/470607085), the `dotfiles` script ran from start to end without prompting for a password.
