### ISSUE TITLE
Script failed when cloning main dotfiles repo

### ISSUE THREAD

**Issue by nunofgs** [uphold/strap#6]
<img width="562" alt="screenshot 2018-11-13 at 21 55 27" src="https://user-images.githubusercontent.com/92085/49522044-a4e82a80-f89e-11e8-9569-4aee7f1a2e8e.png">

**Comment by ricardobcl** [comment]
I'm pretty sure this was an error on the dotfiles project, specifically the `killall mds` did not have `sudo` at the time, as threw an error.

The good news is that [PR 7](https://github.com/uphold/strap/pull/7) introduces a way for the `--debug` flag to also debug the script files called in the cloned dotfiles.
Newer issues will be easier to debug because of this.
